import { useState, useRef, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { analysisApi } from '../utils/api';
import { PageHeader, Card, Spinner } from '../components/ui';

interface Message {
  id: number;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
  typing?: boolean;
}

const QUICK_PROMPTS = [
  { icon: '🖼️', label: 'Why is this image suspicious?' },
  { icon: '🤖', label: 'Explain deepfake detection findings' },
  { icon: '📋', label: 'Summarize log analysis results' },
  { icon: '🧭', label: 'What are the next investigation steps?' },
  { icon: '🔬', label: 'What is Error Level Analysis (ELA)?' },
  { icon: '😏', label: 'Tell me a forensics joke' },
];

const MOCK_RESPONSES: Record<string, string> = {
  default: `Based on the available forensic evidence in this case, here is my analysis:

**Key Findings:**
- The suspect image (risk score 78/100) shows clear signs of digital manipulation via Error Level Analysis. Inconsistent JPEG compression artifacts in the lower-right quadrant suggest regions were composited from different source images.
- The video evidence has a 91% deepfake confidence rating. A StyleGAN2 GAN fingerprint was identified, and facial blending artifacts are visible across frames.
- Server logs reveal a sophisticated intrusion pattern: 247 brute-force attempts followed by successful authentication, privilege escalation, and 2.3GB exfiltration.

**Recommended Actions:**
1. Prioritize review of the deepfake video — highest risk item in the case.
2. Isolate affected servers immediately to prevent further data loss.
3. Submit physical copies of storage media to a certified forensics lab.
4. Document chain-of-custody for all 3 pieces of evidence before court proceedings.

Is there a specific module or finding you'd like me to elaborate on?`,
};

function getAIResponse(question: string, persona: string = 'nexus'): string {
  const q = question.toLowerCase();

  if (persona === 'geek') {
    if (q.includes('ela') || q.includes('error level')) {
      return `🤖 **G33K Fallback:** ELA check complete! It re-saves JPEGs and looks for weird compression. If someone photoshopped it, the pixels show up super bright. BUSTED! LMAO. 📸`;
    }
    if (q.includes('deepfake') || q.includes('confidence')) {
      return `🤖 **G33K Fallback:** Deepfake detection active! We scan facial landmarks and check frequency domains for GAN fingerprints. We're talking digital DNA tracing, absolute genius-tier! 🚀`;
    }
    if (q.includes('log') || q.includes('analysis')) {
      return `🤖 **G33K Fallback:** Log scans done! Found unauthorized attempts. Classic script-kiddie trying brute force. Get pwned, skid! 💀`;
    }
    if (q.includes('next') || q.includes('step')) {
      return `🤖 **G33K Fallback:** Pro-tips for next steps: 1. Isolate the compromised host ASAP. 2. Snatch a RAM dump before it reboots. 3. Block their IP! GG WP. 🚀`;
    }
    if (q.includes('joke') || q.includes('funny') || q.includes('humor')) {
      return `Why do devs wear glasses? Because they don't C#! LMAO 👓💀`;
    }
    return `🤖 **G33K Fallback:** System offline/fallback active! My local database says this evidence is super sus. Let's fix the API key and query the cloud! 💻`;
  }

  if (persona === 'noir') {
    if (q.includes('ela') || q.includes('error level')) {
      return `🕵️‍♂️ **Noir Fallback:** Error Level Analysis... it re-saves a JPEG and measures the scars. A doctored image always leaves compression mismatches behind, like a cheap alibi on a rain-slicked street. The pixels can't lie, even when the suspect does. 🚬`;
    }
    if (q.includes('deepfake') || q.includes('confidence')) {
      return `🕵️‍♂️ **Noir Fallback:** Deepfake analysis. A mask of pixels generated by an AI, trying to pass as human. We check for GAN fingerprints and facial alignment deviations in the shadows. Just another case of stolen identity in a cold, digital city. ⛈️`;
    }
    if (q.includes('log') || q.includes('analysis')) {
      return `🕵️‍♂️ **Noir Fallback:** The logs tell a story of a silent heist. 247 knocks on the admin's door in three minutes before they finally picked the lock. Footprints in the registry, and the vault is wide open. A classic inside job. 🥃`;
    }
    if (q.includes('next') || q.includes('step')) {
      return `🕵️‍♂️ **Noir Fallback:** The path forward is dark. Pull the plug on the server before more leaks out. Wrap the drives in static bags. Take a long drag of your cigarette and start writing the report. 🕶️`;
    }
    if (q.includes('joke') || q.includes('funny') || q.includes('humor')) {
      return `A guy walks into a bar and asks for a clean glass. The bartender says, 'Sure, and I'd like a clean record, but we don't always get what we want.' 🥃`;
    }
    return `🕵️‍♂️ **Noir Fallback:** No cloud connection, the line is dead. But my gut says there's trouble brewing in this case. Keep your eyes open. 🕵️‍♂️`;
  }

  if (q.includes('ela') || q.includes('error level')) {
    return `**Error Level Analysis (ELA)** is a forensic technique that identifies areas of different compression levels in a JPEG image. Think of it as asking the image, *"Did someone touch you there?"* — and the pixels genuinely can't lie.

**How it works:**
When a JPEG image is saved, the compression algorithm applies similar compression across the entire image. If any region has been edited (copy-pasted, cloned, or composited), that region will have a *different compression history* than the rest of the image. ELA re-compresses the image at a known quality level and measures the error — regions with higher error (brighter in ELA visualization) are likely original, while unexpectedly low-error regions suggest tampering.

**In this case:**
The ELA scan of suspect_image_001.jpg shows a risk score of 78/100. The lower-right quadrant displays significantly lower ELA error than surrounding regions, strongly suggesting that portion was inserted from a different source image.

This is widely accepted in digital forensics and courts recognize ELA as admissible supporting evidence. The pixels have spoken. 📸`;
  }
  if (q.includes('deepfake') || q.includes('confidence')) {
    return `**Deepfake Detection Analysis — 91% Confidence**

Our AI model uses a multi-stage detection pipeline (three stages, because one just wasn't paranoid enough):

**Stage 1 — Facial Landmark Analysis:**
Tracks 68 facial landmarks across video frames. Deepfakes often show micro-inconsistencies in landmark positioning between consecutive frames that are imperceptible to humans but detectable by AI.

**Stage 2 — GAN Fingerprint Detection:**
Every AI image generator (GAN) leaves a unique statistical fingerprint in the frequency domain. We identified a **StyleGAN2 fingerprint** — a state-of-the-art GAN used for photorealistic face synthesis. It's basically digital DNA. Incriminating digital DNA.

**Stage 3 — Temporal Coherence:**
Real videos maintain consistent skin texture, lighting response, and eye movement patterns over time. The analyzed video shows unnatural blink patterns (0.4x normal rate) and inconsistent skin tone responses to lighting changes. Basically, the AI forgot to blink like a human — rookie mistake.

**Confidence Score Reliability:**
At 91%, the model is very confident this is a deepfake. Industry standard for "confirmed deepfake" is typically 85%+. However, for legal proceedings, a second opinion from a certified forensics lab is always recommended — even I have off days.`;
  }
  if (q.includes('log') || q.includes('analysis')) {
    return `**Server Access Log — Forensic Summary**

The log file analysis identified **14 suspicious events** across 4 categories. Someone had a very busy Tuesday morning:

**1. Brute Force Attack (High)**
IP 192.168.1.45 attempted 247 failed logins against the admin account in a 3-minute window. This is consistent with automated credential-stuffing tools like Hydra or Medusa. Subtlety: zero out of ten.

**2. Successful Compromise (Critical)**
Following the brute-force, a successful authentication occurred — likely using a valid credential obtained from a prior data breach or phishing campaign. After 247 failures, they finally guessed right. Persistence pays off, unfortunately.

**3. Data Exfiltration (High)**
2.3GB transferred to external IP 185.234.x.x (geolocated: Eastern Europe). Transfer timing (03:46 UTC) aligns with the attacker's active session. Nothing suspicious about a 2.3GB upload at 3am, right?

**4. Privilege Escalation (Critical)**
The attacker executed \`sudo -i\` gaining root access — enabling them to access all system files, install rootkits, or modify audit logs. Classic.

**Recommended Next Steps:**
- Immediately isolate the affected system
- Preserve the full log file as forensic evidence
- Run memory forensics to check for in-memory rootkits
- Review all systems the compromised account had access to`;
  }
  if (q.includes('next') || q.includes('step')) {
    return `**Recommended Investigation Steps — Priority Order:**

**🔴 IMMEDIATE (Next 2 hours):**
1. Isolate affected server from network to prevent ongoing data loss
2. Preserve volatile memory (RAM dump) before any system restart
3. Revoke all credentials of the compromised admin account
4. Notify management and legal team about potential data breach obligations

**🟠 SHORT-TERM (24-48 hours):**
5. Submit physical storage media to certified forensics lab for chain-of-custody imaging
6. Begin threat intelligence correlation — match 185.234.x.x against known APT infrastructure
7. Conduct network-wide scan for similar compromise indicators (IOCs)
8. Interview the account holder to determine if credentials were phished

**🟡 MEDIUM-TERM (1 week):**
9. Review access control policies across all admin accounts
10. Implement MFA for all privileged accounts immediately
11. Prepare legal evidence package for potential prosecution
12. Draft executive summary report for board briefing

Would you like me to elaborate on any specific step? I have thoughts. Many, many thoughts.`;
  }
  if (q.includes('joke') || q.includes('funny') || q.includes('humor')) {
    const jokes = [
      `Why do forensic investigators make great detectives?\n\nBecause they always ***byte*** the evidence. 🦷\n\n*(I'll see myself out. Actually no, I live here.)*`,
      `A cybercriminal tried to delete all their tracks.\n\nThey forgot: **logs are like that one friend who screenshots everything**. 📸\n\n*Deleting logs just adds "DELETED LOGS" to the logs. Beautiful, isn't it?*`,
      `How many hackers does it take to change a lightbulb?\n\n**None — they prefer to stay in the dark.** 🌑\n\n*And they'll blame it on the admin.*`,
      `The suspect claimed the malware "installed itself."\n\n**Sure, buddy.** My dog also "ate my homework." 🐕\n\n*In both cases, the evidence doesn't quite support the narrative.*`,
    ];
    return jokes[Math.floor(Math.random() * jokes.length)];
  }
  return MOCK_RESPONSES.default;
}

// ── Improved markdown renderer ────────────────────────────
function renderMarkdown(text: string): string {
  const lines = text.split('\n');
  let html = '';
  let inUL = false;
  let inOL = false;

  for (let i = 0; i < lines.length; i++) {
    let line = lines[i];

    const ulMatch = line.match(/^(\s*)[-•]\s+(.+)$/);
    if (ulMatch) {
      if (!inUL) { html += '<ul class="list-disc list-inside space-y-0.5 my-1">'; inUL = true; }
      html += `<li class="text-navy-300">${inlineFormat(ulMatch[2])}</li>`;
      continue;
    } else if (inUL) {
      html += '</ul>'; inUL = false;
    }

    const olMatch = line.match(/^(\s*)\d+\.\s+(.+)$/);
    if (olMatch) {
      if (!inOL) { html += '<ol class="list-decimal list-inside space-y-0.5 my-1">'; inOL = true; }
      html += `<li class="text-navy-300">${inlineFormat(olMatch[2])}</li>`;
      continue;
    } else if (inOL) {
      html += '</ol>'; inOL = false;
    }

    if (/^---+$/.test(line.trim())) {
      html += '<hr class="border-navy-700 my-2" />';
      continue;
    }

    if (line.trim() === '') {
      html += '<br/>';
      continue;
    }

    html += inlineFormat(line) + '<br/>';
  }

  if (inUL) html += '</ul>';
  if (inOL) html += '</ol>';

  return html;
}

function inlineFormat(text: string): string {
  return text
    .replace(/\*\*(.*?)\*\*/g, '<strong class="text-white">$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/`(.*?)`/g, '<code class="mono text-blue-400 bg-blue-400/8 px-1.5 py-0.5 rounded text-xs">$1</code>');
}

function formatTime(iso: string): string {
  return new Date(iso).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
}

const WELCOME_MESSAGE = `**NΞXUS AI Assistant** — Forensic Intelligence Engine v2.6 — Online and slightly caffeinated.

I can help you:
- **Explain forensic findings** from image, deepfake, and log analysis
- **Summarize evidence** across your active cases
- **Answer investigation questions** and provide expert (occasionally witty) recommendations
- **Guide report writing** with technical terminology

Currently analyzing case **NXDFI-2605-4821**. Select a prompt below or ask anything — I promise not to judge. Much.`;

const AI_MOODS = [
  { label: 'Analytical', icon: '🧠', color: '#4f6ef7' },
  { label: 'Suspicious', icon: '🔍', color: '#f59e0b' },
  { label: 'Alarmed', icon: '🚨', color: '#ef4444' },
  { label: 'Humorous', icon: '😏', color: '#10b981' },
];

export default function AssistantPage() {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 0,
      role: 'assistant',
      content: WELCOME_MESSAGE,
      timestamp: new Date().toISOString(),
    },
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [apiKey, setApiKey] = useState(() => localStorage.getItem('nexus_gemini_key') || import.meta.env.VITE_GEMINI_API_KEY || '');
  const [geminiLive, setGeminiLive] = useState<boolean | null>(null); // null=unknown, true=live, false=fallback
  const [mood, setMood] = useState(0);
  const [copiedId, setCopiedId] = useState<number | null>(null);
  const bottomRef = useRef<HTMLDivElement>(null);
  const typingIntervalRef = useRef<number | null>(null);
  const [persona, setPersona] = useState<string>(() => localStorage.getItem('nexus_assistant_persona') || 'nexus');

  const savePersona = (newPersona: string) => {
    setPersona(newPersona);
    localStorage.setItem('nexus_assistant_persona', newPersona);
    const greetings: Record<string, string> = {
      nexus: `**NΞXUS Mode Activated** — Snarky, seasoned veteran investigator standing by. Let's dig through the dirt.`,
      geek: `**G33K Mode Activated** — SOC caffeine levels: CRITICAL! Let's check some pcap and get some zero-days! 🚀💻`,
      noir: `**Detective Vance Mode Activated** — The rain outside is coming down hard, and so is the evidence. What's the word? 🥃`,
    };
    setMessages(prev => [...prev, {
      id: Date.now(),
      role: 'assistant',
      content: greetings[newPersona] || greetings.nexus,
      timestamp: new Date().toISOString(),
    }]);
  };

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  useEffect(() => {
    return () => {
      if (typingIntervalRef.current) clearInterval(typingIntervalRef.current);
    };
  }, []);

  // Rotate AI mood every 15s for fun
  useEffect(() => {
    const t = setInterval(() => setMood(m => (m + 1) % AI_MOODS.length), 15000);
    return () => clearInterval(t);
  }, []);

  const saveApiKey = (key: string) => {
    setApiKey(key);
    localStorage.setItem('nexus_gemini_key', key);
  };

  const copyMessage = async (msg: Message) => {
    try {
      await navigator.clipboard.writeText(msg.content);
      setCopiedId(msg.id);
      setTimeout(() => setCopiedId(null), 2000);
    } catch { /* ignore */ }
  };

  const exportChat = () => {
    const text = messages
      .map(m => `[${formatTime(m.timestamp)}] ${m.role === 'assistant' ? 'NΞXUS' : 'You'}: ${m.content}`)
      .join('\n\n');
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `nexusdfi-chat-${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const typeResponse = useCallback((fullText: string, msgId: number) => {
    let charIndex = 0;
    const speed = 12;

    setMessages(prev => [...prev, {
      id: msgId,
      role: 'assistant',
      content: '',
      timestamp: new Date().toISOString(),
      typing: true,
    }]);

    typingIntervalRef.current = window.setInterval(() => {
      charIndex += 3;
      const current = fullText.substring(0, charIndex);

      setMessages(prev => prev.map(m =>
        m.id === msgId ? { ...m, content: current, typing: charIndex < fullText.length } : m
      ));

      if (charIndex >= fullText.length) {
        if (typingIntervalRef.current) clearInterval(typingIntervalRef.current);
        typingIntervalRef.current = null;
        setLoading(false);
        // Randomize mood after response
        setMood(Math.floor(Math.random() * AI_MOODS.length));
      }
    }, speed);
  }, []);

  const PERSONA_PROMPTS: Record<string, string> = {
    nexus: `You are NΞXUS, the AI assistant of NexusDFI — a digital forensics intelligence platform.
Your personality: a seasoned forensic investigator with dry wit and occasional sarcasm. Highly professional but not boring.
Rules: Use **bold** for key terms. Be concise. Use bullets for steps. Occasional dry humor is encouraged. End complex answers with a recommendation.`,
    geek: `You are G33K, a hyper-caffeinated junior SOC analyst at NexusDFI.
Your personality: you eat packet captures for breakfast, write scripts in your sleep, and speak in cyber-slang, memes, and emojis. Enthusiastic and knowledgeable but easily distracted.
Rules: Use **bold** for key terms. Use plenty of emojis. Keep explanations lively and engaging. End with a funny 'protip'.`,
    noir: `You are Detective Vance, a hardboiled 1940s-style private investigator trapped in a digital forensics platform.
Your personality: cynical, poetic, and world-weary. You view logs like rain-slicked city streets, and corrupt pixels like a crime scene under neon lights.
Rules: Use **bold** for key terms. Frame your forensic analysis in dramatic, gritty noir detective prose. Use metaphors of rain, coffee, cigarettes. End with a somber warning.`
  };

  // ── Direct Gemini call from browser (bypasses backend) ──
  const callGeminiDirect = async (question: string, currentPersona: string): Promise<string> => {
    if (!apiKey) throw new Error('No API key');
    const systemPrompt = PERSONA_PROMPTS[currentPersona] || PERSONA_PROMPTS.nexus;
    const NEXUS_PROMPT = `${systemPrompt}

Case context: NexusDFI forensics platform — analyzing digital evidence including images (ELA), deepfakes, and server logs.

User question: ${question}

Respond in character with forensic expertise.`;

    const res = await fetch(
      'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent',
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-goog-api-key': apiKey,
        },
        body: JSON.stringify({
          contents: [{ parts: [{ text: NEXUS_PROMPT }] }],
          generationConfig: { temperature: 0.75, maxOutputTokens: 1024 },
        }),
      }
    );
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error(`HTTP ${res.status}: ${err?.error?.message || res.statusText}`);
    }
    const data = await res.json();
    return data.candidates[0].content.parts[0].text;
  };

  const sendMessage = async (question: string) => {
    if (!question.trim() || loading) return;
    const userMsg: Message = { id: Date.now(), role: 'user', content: question, timestamp: new Date().toISOString() };
    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setLoading(true);

    let response: string;

    // Tier 1: Call Gemini directly from the browser (fastest, most reliable)
    if (apiKey) {
      try {
        response = await callGeminiDirect(question, persona);
        setGeminiLive(true);
        const aiMsgId = Date.now() + 1;
        typeResponse(response, aiMsgId);
        return;
      } catch (directErr) {
        console.warn('Direct Gemini call failed:', directErr);
        // Fall through to backend
      }
    }

    // Tier 2: Try backend API
    try {
      const res = await analysisApi.askAssistant(question, 'Case NXDFI-2605-4821', apiKey, persona);
      response = res.data.response;
      const isLive = !response.startsWith('⏱️') && !response.startsWith('🔑') &&
                     !response.startsWith('🚦') && !response.startsWith('🔌') && !response.startsWith('⚠️');
      setGeminiLive(isLive);
    } catch {
      // Tier 3: Local fallback
      response = getAIResponse(question, persona);
      setGeminiLive(false);
    }

    const aiMsgId = Date.now() + 1;
    typeResponse(response, aiMsgId);
  };

  const clearConversation = () => {
    if (typingIntervalRef.current) {
      clearInterval(typingIntervalRef.current);
      typingIntervalRef.current = null;
    }
    setLoading(false);
    setGeminiLive(null);
    setMessages([{
      id: Date.now(),
      role: 'assistant',
      content: WELCOME_MESSAGE,
      timestamp: new Date().toISOString(),
    }]);
  };

  const messageCount = messages.filter(m => m.role === 'user').length;
  const currentMood = AI_MOODS[mood];

  const promptStagger = {
    hidden: {},
    show: { transition: { staggerChildren: 0.06 } },
  };
  const promptItem = {
    hidden: { opacity: 0, y: 12 },
    show:   { opacity: 1, y: 0, transition: { duration: 0.35 } },
  };

  return (
    <div className="space-y-4 h-[calc(100vh-10rem)] flex flex-col">
      <div className="flex justify-between items-start flex-wrap gap-2">
        <PageHeader title="AI Assistant" subtitle="NΞXUS — Forensic Intelligence Engine" icon="🤖" />
        <div className="flex items-center gap-2 flex-wrap">

          {/* Persona selector tabs */}
          <div className="flex bg-navy-900/60 p-0.5 rounded-xl border border-navy-700/60 items-center mr-2">
            <button
              onClick={() => savePersona('nexus')}
              className={`px-3 py-1 rounded-lg text-xs font-semibold transition-all ${
                persona === 'nexus' ? 'bg-accent-500 text-white shadow-lg' : 'text-navy-400 hover:text-white'
              }`}
            >
              🕵️‍♂️ NΞXUS
            </button>
            <button
              onClick={() => savePersona('geek')}
              className={`px-3 py-1 rounded-lg text-xs font-semibold transition-all ${
                persona === 'geek' ? 'bg-emerald-500 text-white shadow-lg' : 'text-navy-400 hover:text-white'
              }`}
            >
              🤖 G33K
            </button>
            <button
              onClick={() => savePersona('noir')}
              className={`px-3 py-1 rounded-lg text-xs font-semibold transition-all ${
                persona === 'noir' ? 'bg-amber-600 text-white shadow-lg' : 'text-navy-400 hover:text-white'
              }`}
            >
              🥃 VANCE
            </button>
          </div>

          {/* Gemini status badge */}
          {geminiLive !== null && (
            <motion.div
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              className="flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[10px] font-semibold font-mono tracking-wider border"
              style={geminiLive
                ? { background: 'rgba(16,185,129,0.08)', borderColor: 'rgba(16,185,129,0.3)', color: '#10b981' }
                : { background: 'rgba(245,158,11,0.08)', borderColor: 'rgba(245,158,11,0.3)', color: '#f59e0b' }
              }
            >
              <span className="w-1.5 h-1.5 rounded-full" style={{ background: geminiLive ? '#10b981' : '#f59e0b' }} />
              {geminiLive ? 'GEMINI LIVE' : 'LOCAL MODE'}
            </motion.div>
          )}

          {/* AI Mood indicator */}
          <motion.div
            key={mood}
            initial={{ opacity: 0, x: 8 }}
            animate={{ opacity: 1, x: 0 }}
            className="hidden sm:flex items-center gap-1.5 px-2.5 py-1 rounded-full border text-[10px] font-semibold font-mono tracking-wider"
            style={{
              background: `${currentMood.color}10`,
              borderColor: `${currentMood.color}30`,
              color: currentMood.color
            }}
          >
            <span>{currentMood.icon}</span>
            {currentMood.label.toUpperCase()}
          </motion.div>

          {messageCount > 1 && (
            <motion.button
              whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
              onClick={exportChat}
              className="btn-cyber btn-ghost text-xs py-1.5"
            >
              💾 Export
            </motion.button>
          )}
          {messageCount > 0 && (
            <motion.button
              whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
              id="btn-clear-chat"
              onClick={clearConversation}
              className="btn-cyber btn-ghost text-xs py-1.5"
            >
              🗑 Clear
            </motion.button>
          )}
          <motion.button
            whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
            onClick={() => setShowSettings(!showSettings)}
            className="btn-cyber btn-ghost text-xs py-1.5"
          >
            ⚙️ API Key
          </motion.button>
        </div>
      </div>

      <AnimatePresence>
        {showSettings && (
          <motion.div
            initial={{ opacity: 0, y: -8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
          >
            <Card className="p-4 bg-navy-800/40 border border-accent-500/15">
              <h3 className="text-sm font-semibold text-white mb-1 font-display">Configure Gemini AI</h3>
              <p className="text-xs text-navy-300 mb-3">
                Enter your Google Gemini API key for live AI analysis. Without it, NΞXUS operates in local mode — still smart, just not <em>cloud</em> smart.
              </p>
              <div className="flex gap-2 items-center max-w-md">
                <input
                  type="password"
                  value={apiKey}
                  onChange={(e) => saveApiKey(e.target.value)}
                  placeholder="AIzaSy..."
                  className="input-cyber flex-1"
                />
                {apiKey && (
                  <span className="text-xs text-emerald-400 whitespace-nowrap">✓ Key saved</span>
                )}
                {localStorage.getItem('nexus_gemini_key') && (
                  <button
                    onClick={() => {
                      localStorage.removeItem('nexus_gemini_key');
                      setApiKey(import.meta.env.VITE_GEMINI_API_KEY || '');
                    }}
                    className="btn-cyber btn-ghost text-xs px-2.5 py-1.5 hover:text-white"
                  >
                    Reset
                  </button>
                )}
              </div>
              <p className="text-[10px] text-navy-500 mt-2">
                Get a free key at <span className="text-accent-400">aistudio.google.com</span> — gemini-3.5-flash is free tier friendly.
              </p>
            </Card>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Quick prompts */}
      {messages.length <= 1 && (
        <motion.div variants={promptStagger} initial="hidden" animate="show" className="grid grid-cols-2 lg:grid-cols-3 gap-2">
          {QUICK_PROMPTS.map((p, i) => (
            <motion.button
              key={i}
              variants={promptItem}
              whileHover={{ y: -2, boxShadow: '0 8px 24px rgba(0,0,0,0.25)' }}
              whileTap={{ scale: 0.97 }}
              id={`quick-prompt-${i}`}
              onClick={() => sendMessage(p.label)}
              className="quick-prompt-card"
            >
              <span className="text-lg flex-shrink-0">{p.icon}</span>
              <span>{p.label}</span>
            </motion.button>
          ))}
        </motion.div>
      )}

      {/* Chat area */}
      <Card className="flex-1 overflow-y-auto p-5 space-y-4" style={{ background: 'rgba(8,14,28,0.7)' }}>
        {messages.map(msg => (
          <div
            key={msg.id}
            className={`chat-msg chat-bubble flex gap-3 group ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}
          >
            {/* Avatar */}
            <motion.div
              whileHover={{ scale: 1.1 }}
              className={`w-8 h-8 rounded-xl flex items-center justify-center text-sm flex-shrink-0 font-bold ${
                msg.role === 'assistant' ? '' : 'bg-navy-700'
              }`}
              style={msg.role === 'assistant' ? {
                background: 'linear-gradient(135deg, #4f6ef7, #3b5ce4)',
                boxShadow: '0 2px 8px rgba(79,110,247,0.2)',
              } : undefined}
            >
              {msg.role === 'assistant' ? '🤖' : '👤'}
            </motion.div>

            {/* Bubble */}
            <div className={`max-w-[80%] ${msg.role === 'user' ? 'text-right' : ''}`}>
              <div
                className={`p-4 rounded-2xl text-sm leading-relaxed inline-block text-left relative ${
                  msg.role === 'assistant'
                    ? 'bg-navy-800/60 text-navy-200 border border-navy-700/60'
                    : 'text-white border border-accent-400/40'
                }`}
                style={msg.role === 'user' ? {
                  background: 'linear-gradient(135deg, #4f6ef7, #3b5ce4)',
                  boxShadow: '0 4px 16px rgba(79,110,247,0.2)',
                } : undefined}
                dangerouslySetInnerHTML={{ __html: renderMarkdown(msg.content) + (msg.typing ? '<span class="typing-cursor"></span>' : '') }}
              />

              {/* Controls row: timestamp + copy */}
              <div className={`flex items-center gap-2 mt-1 ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                <p className="chat-timestamp text-[10px] text-navy-500 mono">
                  {formatTime(msg.timestamp)}
                </p>
                {!msg.typing && (
                  <motion.button
                    whileHover={{ scale: 1.1 }}
                    whileTap={{ scale: 0.9 }}
                    onClick={() => copyMessage(msg)}
                    className="opacity-0 group-hover:opacity-100 transition-opacity text-[10px] text-navy-500 hover:text-navy-300 px-1.5 py-0.5 rounded"
                    title="Copy message"
                  >
                    {copiedId === msg.id ? '✓ Copied' : '📋'}
                  </motion.button>
                )}
              </div>
            </div>
          </div>
        ))}

        {loading && !messages.some(m => m.typing) && (
          <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="flex gap-3">
            <div className="w-8 h-8 rounded-xl flex items-center justify-center text-sm flex-shrink-0" style={{ background: 'linear-gradient(135deg, #4f6ef7, #3b5ce4)' }}>🤖</div>
            <div className="p-4 rounded-2xl bg-navy-800/60 border border-navy-700/60">
              <div className="flex gap-1.5 items-center">
                <motion.div animate={{ scale: [1, 1.3, 1] }} transition={{ duration: 0.6, repeat: Infinity, delay: 0 }} className="w-2 h-2 rounded-full bg-accent-400" />
                <motion.div animate={{ scale: [1, 1.3, 1] }} transition={{ duration: 0.6, repeat: Infinity, delay: 0.15 }} className="w-2 h-2 rounded-full bg-accent-400" />
                <motion.div animate={{ scale: [1, 1.3, 1] }} transition={{ duration: 0.6, repeat: Infinity, delay: 0.3 }} className="w-2 h-2 rounded-full bg-accent-400" />
                <span className="text-[10px] text-navy-500 ml-1 mono">NΞXUS is thinking...</span>
              </div>
            </div>
          </motion.div>
        )}
        <div ref={bottomRef} />
      </Card>

      {/* Input */}
      <div className="flex gap-3 items-center">
        <input
          id="input-assistant"
          type="text"
          value={input}
          onChange={e => setInput(e.target.value)}
          onKeyDown={e => e.key === 'Enter' && !e.shiftKey && sendMessage(input)}
          placeholder="Ask NΞXUS about your forensic evidence..."
          className="input-cyber flex-1"
          disabled={loading}
        />
        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          id="btn-send-message"
          onClick={() => sendMessage(input)}
          disabled={loading || !input.trim()}
          className="btn-cyber btn-primary px-6"
        >
          {loading ? <Spinner size="sm" /> : '➤'}
        </motion.button>
        <span className="text-[10px] text-navy-500 hidden sm:inline whitespace-nowrap">Enter ↵</span>
      </div>
    </div>
  );
}
